# Generated by Django 4.1.2 on 2023-04-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_ingredients_instructionset_step_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='instruction_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.instructionset'),
        ),
    ]
