# Generated by Django 4.1.3 on 2023-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe_image.jpg', upload_to='recipe_images/'),
        ),
    ]
